site_name: My Recipes
theme:
  name: material
  palette:
    scheme: default
    primary: custom
    accent: amber
  font:
    text: Merriweather
    code: Fira Code

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Dinner:
      - Chicken Burgers: dinner/chicken-burgers.md
  - Pasta:
      - Mackerel Pasta: pasta/mackerel-pasta.md
      - Spinach and Ricotta Pasta: pasta/spinach-and-ricotta-pasta.md
      - Herby Pasta: pasta/herby-pasta.md
  - Batch:
      - Beef and Barley Stew: batch/beef-and-barley-stew.md
